name: IslandRate
main: com.yovez.islandrate.IslandRate
version: 1.3.3.7.1
author: Yovez
depend: [BentoBox]
softdepend: [PlaceholderAPI]
api-version: 1.13
commands:
    rate:
        description: Rate the island you are at!
