name: IslandRate
main: com.yovez.islandrate.IslandRate
version: 1.3.4.1
author: Yovez
depend: [BentoBox]
softdepend: [PlaceholderAPI]
api-version: 1.14
commands:
    rate:
        description: Rate the island you are at!
